//
//  RWDEFAULTTEXT.h
//  Red Event App
//
//  Created by Thorbjørn Steen on 10/8/13.
//  Copyright (c) 2013 redWEB. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface RWDEFAULTTEXT : NSObject

+(NSString *)ADVENTWINDOW_BACKBUTTON;

+(NSString *)ARTICLEDETAIL_BACKBUTTON;

+ (NSString *)BIKETRACKING_AVERAGESPEED;

+ (NSString *)BIKETRACKING_TOPSPEED;

+ (NSString *)BIKETRACKING_DISTANCE;

+ (NSString *)BIKETRACKING_BACKBUTTON;

+ (NSString *)BIKETRACKING_STARTBUTTON;

+ (NSString *)BIKETRACKING_STOPBUTTON;

+ (NSString *)BIKETRACKING_CONTINUEBUTTON;

+ (NSString *)BIKETRACKING_RUNNING;

+ (NSString *)BIKETRACKING_STOPPED;

+(NSString *)DAILYSESSIONLIST_EMPTYLIST;
+(NSString *)DAILYSESSIONLIST_FILTERDATE;

+(NSString *)IMAGEARTICLELIST_EMPTYLIST;

+(NSString *)MAPVIEW_BACKBUTTON;

+(NSString *)NEWSTICKER_TITLE;

+(NSString *)PUSHMESSAGEDETAIL_BACKBUTTON;

+(NSString *)SESSIONDETAIL_DATE;
+(NSString *)SESSIONDETAIL_PLACE;
+(NSString *)SESSIONDETAIL_TIME;
+(NSString *)SESSIONDETAIL_MAPBUTTON;

+(NSString *)UPCOMINGSESSIONS_TITLE;

+(NSString *)VENUEDETAIL_ADDRESS;
+(NSString *)VENUEDETAIL_MAPBUTTON;

+ (NSString *)WEBVIEW_BACKBUTTON;
@end
