//
//  RWLOOK.h
//  Red Event App
//
//  Created by Thorbjørn Steen on 9/27/13.
//  Copyright (c) 2013 redWEB. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface RWLOOK : NSObject

+ (NSString *)APPEARANCEFILENAME;

//Color Constants
+ (NSString *)INVISIBLE;

//Gui Constants
+ (NSString *)SCROLLBOUNCES;

//Style Constants
+ (NSString *)TYPEFACE_BOLD;
+ (NSString *)TYPEFACE_BOLD_ITALIC;
+ (NSString *)TYPEFACE_ITALIC;
+ (NSString *)TYPEFACE_NORMAL;

//Global
+ (NSString *)BACKBUTTONBACKGROUNDCOLOR;
+ (NSString *)BACKBUTTONBACKGROUNDIMAGE;
+ (NSString *)BACKBUTTONICON;
+ (NSString *)BACKBUTTONTEXTCOLOR;
+ (NSString *)BACKBUTTONTEXTSHADOWCOLOR;
+ (NSString *)BACKBUTTONTEXTSHADOWOFFSET;
+ (NSString *)BACKBUTTONTEXTSIZE;
+ (NSString *)BACKBUTTONTEXTSTYLE;
+ (NSString *)BACKGROUNDCOLOR;
+ (NSString *)BACKGROUNDIMAGE;

+ (NSString *)BUTTONBACKGROUNDCOLOR;
+ (NSString *)BUTTONBACKGROUNDIMAGE;
+ (NSString *)BUTTONICON;
+ (NSString *)BUTTONTEXTCOLOR;
+ (NSString *)BUTTONTEXTSHADOWCOLOR;
+ (NSString *)BUTTONTEXTSHADOWOFFSET;
+ (NSString *)BUTTONTEXTSIZE;
+ (NSString *)BUTTONTEXTSTYLE;

+ (NSString *)CELLBACKGROUNDCOLOR;
+ (NSString *)ITEMTITLECOLOR;
+ (NSString *)ITEMTITLESHADOWCOLOR;
+ (NSString *)ITEMTITLESHADOWOFFSET;
+ (NSString *)ITEMTITLESIZE;
+ (NSString *)ITEMTITLESTYLE;
+ (NSString *)TEXTCOLOR;
+ (NSString *)TEXTSHADOWCOLOR;
+ (NSString *)TEXTSHADOWOFFSET;
+ (NSString *)TEXTSIZE;
+ (NSString *)TEXTSTYLE;
+ (NSString *)TITLECOLOR;
+ (NSString *)TITLESHADOWCOLOR;
+ (NSString *)TITLESHADOWOFFSET;
+ (NSString *)TITLESIZE;
+ (NSString *)TITLESTYLE;

//Default Snippets for Custom Styles
+ (NSString *)DEFCOLOR_ALT;
+ (NSString *)DEFCOLOR_BACK;
+ (NSString *)DEFCOLOR_BAR;
+ (NSString *)DEFSIZE_ITEMTITLE;
+ (NSString *)DEFSIZE_TEXT;
+ (NSString *)DEFSIZE_TITLE;

+ (NSString *)APPEARANCEHELPER_DEF_COLOR;
+ (NSString *)APPEARANCEHELPER_DEF_TEXTCOLOR;
+ (NSString *)APPEARANCEHELPER_DEF_SHADOWCOLOR;
+ (NSString *)APPEARANCEHELPER_DEF_TEXTSHADOWCOLOR;
+ (NSString *)APPEARANCEHELPER_DEF_SHADOWOFFSET;
+ (NSString *)APPEARANCEHELPER_DEF_TEXTSHADOWOFFSET;
+ (NSString *)APPEARANCEHELPER_DEF_SIZE;
+ (NSString *)APPEARANCEHELPER_DEF_STYLE;

//Default
+ (NSString *)DEFAULT;
+ (NSString *)DEFAULT_ALTCOLOR;
+ (NSString *)DEFAULT_ALTTEXTCOLOR;
+ (NSString *)DEFAULT_ALTTEXTSHADOWCOLOR;
+ (NSString *)DEFAULT_BACKCOLOR;
+ (NSString *)DEFAULT_BACKTEXTCOLOR;
+ (NSString *)DEFAULT_BACKTEXTSHADOWCOLOR;
+ (NSString *)DEFAULT_BARCOLOR;
+ (NSString *)DEFAULT_BARTEXTCOLOR;
+ (NSString *)DEFAULT_BARTEXTSHADOWCOLOR;
+ (NSString *)DEFAULT_ITEMTITLESHADOWOFFSET;
+ (NSString *)DEFAULT_ITEMTITLESIZE;
+ (NSString *)DEFAULT_ITEMTITLESTYLE;
+ (NSString *)DEFAULT_TEXTSHADOWOFFSET;
+ (NSString *)DEFAULT_TEXTSIZE;
+ (NSString *)DEFAULT_TEXTSTYLE;
+ (NSString *)DEFAULT_TITLESHADOWOFFSET;
+ (NSString *)DEFAULT_TITLESIZE;
+ (NSString *)DEFAULT_TITLESTYLE;

//Navigationbar
+ (NSString *)NAVIGATIONBAR;
+ (NSString *)NAVBAR_BACKGROUNDCOLOR;
+ (NSString *)NAVBAR_BACKGROUNDIMAGE;
+ (NSString *)NAVBAR_HASTITLE;
+ (NSString *)NAVBAR_HOMEBUTTONBACKIMAGE;
+ (NSString *)NAVBAR_HOMEBUTTONCOLOR;
+ (NSString *)NAVBAR_HOMEBUTTONIMAGE;
+ (NSString *)NAVBAR_HOMEBUTTONTEXTCOLOR;
+ (NSString *)NAVBAR_HOMEBUTTONTEXTSHADOWCOLOR;
+ (NSString *)NAVBAR_HOMEBUTTONTEXTSHADOWOFFSET;
+ (NSString *)NAVBAR_HOMEBUTTONTEXTSIZE;
+ (NSString *)NAVBAR_HOMEBUTTONTEXTSTYLE;
+ (NSString *)NAVBAR_TITLECOLOR;
+ (NSString *)NAVBAR_TITLESIZE;
+ (NSString *)NAVBAR_TITLESTYLE;
+ (NSString *)NAVBAR_TITLESHADOWCOLOR;
+ (NSString *)NAVBAR_TITLESHADOWOFFSET;
+ (NSString *)NAVBAR_UPBUTTONBACKIMAGE;
+ (NSString *)NAVBAR_UPBUTTONCOLOR;
+ (NSString *)NAVBAR_UPBUTTONIMAGE;
+ (NSString *)NAVBAR_UPBUTTONTEXTCOLOR;
+ (NSString *)NAVBAR_UPBUTTONTEXTSHADOWCOLOR;
+ (NSString *)NAVBAR_UPBUTTONTEXTSHADOWOFFSET;
+ (NSString *)NAVBAR_UPBUTTONTEXTSIZE;
+ (NSString *)NAVBAR_UPBUTTONTEXTSTYLE;
+ (NSString *)NAVBAR_VISIBLE;

//Tabbar
+ (NSString *)TABBAR;
+ (NSString *)TABBAR_BACKGROUNDCOLOR;
+ (NSString *)TABBAR_BACKGROUNDIMAGE;
+ (NSString *)TABBAR_TEXTCOLOR;
+ (NSString *)TABBAR_TEXTSHADOWCOLOR;
+ (NSString *)TABBAR_TEXTSHADOWOFFSET;
+ (NSString *)TABBAR_TEXTSIZE;
+ (NSString *)TABBAR_TEXTSTYLE;
+ (NSString *)TABBAR_VISIBLE;


//ButtonGallery
+ (NSString *)BUTTONGALLERY_BUTTON1BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON1ICON;
+ (NSString *)BUTTONGALLERY_BUTTON2BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON2ICON;
+ (NSString *)BUTTONGALLERY_BUTTON3BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON3ICON;
+ (NSString *)BUTTONGALLERY_BUTTON4BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON4ICON;
+ (NSString *)BUTTONGALLERY_BUTTON5BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON5ICON;
+ (NSString *)BUTTONGALLERY_BUTTON6BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON6ICON;
+ (NSString *)BUTTONGALLERY_BUTTON7BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON7ICON;
+ (NSString *)BUTTONGALLERY_BUTTON8BACKGROUNDIMAGE;
+ (NSString *)BUTTONGALLERY_BUTTON8ICON;

//DailySessionList
+ (NSString *)DAILYSESSIONLIST_BACKGROUNDCOLOR;
+ (NSString *)DAILYSESSIONLIST_LEFTARROW;
+ (NSString *)DAILYSESSIONLIST_RIGHTARROW;
+ (NSString *)DAILYSESSIONLIST_DATETEXTCOLOR;
+ (NSString *)DAILYSESSIONLIST_DATETEXTSHADOWCOLOR;
+ (NSString *)DAILYSESSIONLIST_DATETEXTSHADOWOFFSET;
+ (NSString *)DAILYSESSIONLIST_DATETEXTSIZE;
+ (NSString *)DAILYSESSIONLIST_DATETEXTSTYLE;
+ (NSString *)DAILYSESSIONLIST_DATEUNDERLINECOLOR;

//PushMessageDetail
+ (NSString *)PUSHMESSAGEDETAIL_AUTHORTEXTSHADOWCOLOR;
+ (NSString *)PUSHMESSAGEDETAIL_AUTHORTEXTSHADOWOFFSET;
+ (NSString *)PUSHMESSAGEDETAIL_AUTHORTEXTCOLOR;
+ (NSString *)PUSHMESSAGEDETAIL_AUTHORTEXTSIZE;
+ (NSString *)PUSHMESSAGEDETAIL_AUTHORTEXTSTYLE;
+ (NSString *)PUSHMESSAGEDETAIL_SENTTEXTSHADOWCOLOR;
+ (NSString *)PUSHMESSAGEDETAIL_SENTTEXTSHADOWOFFSET;
+ (NSString *)PUSHMESSAGEDETAIL_SENTTEXTCOLOR;
+ (NSString *)PUSHMESSAGEDETAIL_SENTTEXTSIZE;
+ (NSString *)PUSHMESSAGEDETAIL_SENTTEXTSTYLE;

//SessionDetail
+ (NSString *)SESSIONDETAIL_LABELCOLOR;
+ (NSString *)SESSIONDETAIL_LABELSHADOWCOLOR;
+ (NSString *)SESSIONDETAIL_LABELSHADOWOFFSET;
+ (NSString *)SESSIONDETAIL_LABELSIZE;
+ (NSString *)SESSIONDETAIL_LABELSTYLE;

//StyledSessionList
+(NSString *)STYLEDSESSIONLIST_LISTBACKGROUNDCOLOR;
+(NSString *)STYLEDSESSIONLIST_LISTLINECOLOR;
+(NSString *)STYLEDSESSIONLIST_CAMERABUTTONIMAGE;
+(NSString *)STYLEDSESSIONLIST_ARCHIVEBUTTONIMAGE;

//SwipeView
+ (NSString *)SWIPEVIEW_SELECTEDPAGECOLOR;
+ (NSString *)SWIPEVIEW_UNSELECTEDPAGECOLOR;

//VenueDetail
+ (NSString *)VENUEDETAIL_LABELCOLOR;
+ (NSString *)VENUEDETAIL_LABELSHADOWCOLOR;
+ (NSString *)VENUEDETAIL_LABELSHADOWOFFSET;
+ (NSString *)VENUEDETAIL_LABELSIZE;
+ (NSString *)VENUEDETAIL_LABELSTYLE;
@end
