//
//  RWTEXT.h
//  Red Event App
//
//  Created by Thorbjørn Steen on 10/8/13.
//  Copyright (c) 2013 redWEB. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface RWTEXT : NSObject

+(NSString *)TEXTFILENAME;

+(NSString *)NAVBAR_HOMEBUTTON;
+(NSString *)NAVBAR_UPBUTTON;

+(NSString *)ADVENTWINDOW_BACKBUTTON;

+(NSString *)ARTICLEDETAIL_BACKBUTTON;

+ (NSString *)BIKETRACKING_AVERAGESPEED;
+ (NSString *)BIKETRACKING_TOPSPEED;
+ (NSString *)BIKETRACKING_DISTANCE;
+ (NSString *)BIKETRACKING_BACKBUTTON;
+ (NSString *)BIKETRACKING_STARTBUTTON;
+ (NSString *)BIKETRACKING_STOPBUTTON;
+ (NSString *)BIKETRACKING_CONTINUEBUTTON;
+ (NSString *)BIKETRACKING_RUNNING;
+ (NSString *)BIKETRACKING_STOPPED;

+(NSString *)BUTTONGALLERY_BUTTON1;
+(NSString *)BUTTONGALLERY_BUTTON2;
+(NSString *)BUTTONGALLERY_BUTTON3;
+(NSString *)BUTTONGALLERY_BUTTON4;
+(NSString *)BUTTONGALLERY_BUTTON5;
+(NSString *)BUTTONGALLERY_BUTTON6;
+(NSString *)BUTTONGALLERY_BUTTON7;
+(NSString *)BUTTONGALLERY_BUTTON8;

+ (NSString *)CAMERAINTENT_CAMERABUTTON;

+(NSString *)DAILYSESSIONLIST_FILTERDATE;

+(NSString *)IMAGEUPLOADER_BROWSERBUTTON;
+(NSString *)IMAGEUPLOADER_UPLOADBUTTON;

+(NSString *)MAPVIEW_BACKBUTTON;

+ (NSString *)PUSHMESSAGEDETAIL_BACKBUTTON;

+(NSString *)SESSIONDETAIL_DATE;
+(NSString *)SESSIONDETAIL_PLACE;
+(NSString *)SESSIONDETAIL_TIME;
+(NSString *)SESSIONDETAIL_MAPBUTTON;

+(NSString *)VENUEDETAIL_ADDRESS;
+(NSString *)VENUEDETAIL_MAPBUTTON;

+ (NSString *)WEBVIEW_BACKBUTTON;
@end
